name: Doctests on slides

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Doctest on rakus March readable LT slide
        run: |
          cd source/rakus_Mar_readable
          python -m doctest mapping_wrapper.rst -v
      - name: Doctest on rakus May Python Tips LT slide
        run: |
          cd source/rakus_May_pythontips
          python -m doctest unpack_operators.rst.txt function_with_stars.rst.txt -v
      - name: Doctest on rakus Jun OOLT slide
        run: |
          cd source/rakus_Jun_oo
          python -m doctest minodriven_book_circle.rst -v
      - name: Doctest on PyCon JP 2022 slide
        run: python -m doctest source/pyconjp/*.rst.txt source/pyconjp/tips/*.rst.txt samplecode/superstar/customize_mul.py -v
      - name: Doctest on Hannari Programming LT slide
        run: |
          cd samplecode/normalizers
          python -m doctest assembled.py -v
          cd ../..
          cd source/hannari_Dec
          python -m doctest neologd_normalization.rst.txt implementation_proposal.rst.txt -v
