name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
      - name: Build slide
        run: |
          pip install sphinx_revealjs
          # Copy revealjs4 directory under _static
          make revealjs
          touch build/revealjs/.nojekyll
          pip uninstall sphinx_revealjs -y
          pip install -r requirements.in
          # emphasize-lines enable build
          make revealjs
          rm -r build/revealjs/_sources
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0-alpha
        with:
          build_dir: build/revealjs
          github_token: ${{ secrets.GITHUB_TOKEN }}
